# -*- coding: utf-8 -*-
"""Building-Your-Own-Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RiGr6bAk7TAkDmdufk0sNlhWlQwD1SGa
"""

#project: a chat bot program

#importing libraries
from nltk.chat.util import Chat, reflections

#defining a list of patterns
pairs= [
    ['my name is (.*)', ['hi %1']],
    ['(hi|hello|hey|holla|hola)', ['hey there', 'hii', 'hello', 'haayyy']],
    ['(.*) in (.*) is fun', ['%1 in %2 is indeed fun!']],
    ['(.*) created you?', ['alisha did']],
    ['how is weather in (.*)', ['weather in %1 is pleasant as always!']],
    ['(.*) name?', ['my name is alisha']],
    ['(.*) qualification?', ['i am pursuing engineering in computer science']],
    ['(.*) work?', ['no, i am a student']]
]

chat= Chat(pairs, reflections)#initializing a chatbot instance with the provided patterns (pairs) and reflections (reflections)
chat.converse()#starting an interactive session where the chatbot engages in a conversation with the user